-- Personal Trainer Agent — Supabase Schema
-- Run this in your Supabase SQL editor to set up the tables.

-- User profile: weight, age, goals, injuries, equipment, etc.
create table if not exists trainer_profiles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  age integer,
  weight_kg numeric,
  height_cm numeric,
  fitness_goal text,          -- e.g. "build muscle", "lose fat", "general fitness"
  experience_level text,      -- beginner, intermediate, advanced
  injuries_notes text,        -- any injuries or limitations
  available_equipment text,   -- e.g. "full gym", "dumbbells only", "bodyweight"
  days_per_week integer default 3,
  notes text,                 -- anything else (past trainer notes, preferences)
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Exercise library: each exercise with optional video link
create table if not exists exercises (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  muscle_group text,          -- e.g. "chest", "back", "legs", "shoulders", "arms", "core"
  equipment text,             -- e.g. "barbell", "dumbbell", "cable", "bodyweight"
  video_url text,             -- YouTube or other video link
  description text,
  created_at timestamptz default now()
);

-- Workout plans generated by the AI
create table if not exists workout_plans (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references trainer_profiles(id) on delete cascade,
  week_start date not null,   -- Monday of the week this plan covers
  day_number integer not null, -- 1, 2, or 3 (which session of the week)
  day_label text,             -- e.g. "Push", "Pull", "Legs"
  workout_json jsonb not null, -- full workout structure from AI
  notes text,                 -- AI-generated tips or notes for the day
  created_at timestamptz default now()
);

-- Workout log: what the user actually did
create table if not exists workout_logs (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references trainer_profiles(id) on delete cascade,
  plan_id uuid references workout_plans(id) on delete set null,
  completed_at timestamptz default now(),
  exercises_json jsonb,       -- what was actually performed (sets/reps/weight)
  feeling text,               -- "easy", "moderate", "hard", "exhausted"
  notes text
);

-- Seed some common exercises
insert into exercises (name, muscle_group, equipment, video_url, description) values
  ('Barbell Bench Press', 'chest', 'barbell', 'https://www.youtube.com/watch?v=rT7DgCr-3pg', 'Flat bench press with barbell'),
  ('Incline Dumbbell Press', 'chest', 'dumbbell', 'https://www.youtube.com/watch?v=8iPEnn-ltC8', 'Incline press with dumbbells at 30-45 degrees'),
  ('Cable Flyes', 'chest', 'cable', 'https://www.youtube.com/watch?v=Iwe6AmxVf7o', 'Cable crossover flyes for chest isolation'),
  ('Barbell Squat', 'legs', 'barbell', 'https://www.youtube.com/watch?v=ultWZbUMPL8', 'Back squat with barbell'),
  ('Romanian Deadlift', 'legs', 'barbell', 'https://www.youtube.com/watch?v=7j-2w4-P14I', 'Hip-hinge movement targeting hamstrings and glutes'),
  ('Leg Press', 'legs', 'machine', 'https://www.youtube.com/watch?v=IZxyjW7MPJQ', '45-degree leg press machine'),
  ('Bulgarian Split Squat', 'legs', 'dumbbell', 'https://www.youtube.com/watch?v=2C-uNgKwPLE', 'Single-leg squat with rear foot elevated'),
  ('Barbell Deadlift', 'back', 'barbell', 'https://www.youtube.com/watch?v=op9kVnSso6Q', 'Conventional deadlift'),
  ('Pull-ups', 'back', 'bodyweight', 'https://www.youtube.com/watch?v=eGo4IYlbE5g', 'Bodyweight pull-up'),
  ('Barbell Row', 'back', 'barbell', 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ', 'Bent-over barbell row'),
  ('Lat Pulldown', 'back', 'cable', 'https://www.youtube.com/watch?v=CAwf7n6Luuc', 'Wide-grip lat pulldown'),
  ('Overhead Press', 'shoulders', 'barbell', 'https://www.youtube.com/watch?v=2yjwXTZQDDI', 'Standing barbell overhead press'),
  ('Lateral Raises', 'shoulders', 'dumbbell', 'https://www.youtube.com/watch?v=3VcKaXpzqRo', 'Dumbbell lateral raises'),
  ('Face Pulls', 'shoulders', 'cable', 'https://www.youtube.com/watch?v=rep-qVOkqgk', 'Cable face pulls for rear delts'),
  ('Barbell Curl', 'arms', 'barbell', 'https://www.youtube.com/watch?v=kwG2ipFRgfo', 'Standing barbell curl for biceps'),
  ('Tricep Pushdown', 'arms', 'cable', 'https://www.youtube.com/watch?v=2-LAMcpzODU', 'Cable tricep pushdown'),
  ('Dumbbell Hammer Curl', 'arms', 'dumbbell', 'https://www.youtube.com/watch?v=zC3nLlEvin4', 'Hammer curls for brachialis and biceps'),
  ('Plank', 'core', 'bodyweight', 'https://www.youtube.com/watch?v=ASdvN_XEl_c', 'Isometric core hold'),
  ('Hanging Leg Raise', 'core', 'bodyweight', 'https://www.youtube.com/watch?v=hdng3Nm1x_E', 'Hanging leg raises for lower abs'),
  ('Cable Woodchop', 'core', 'cable', 'https://www.youtube.com/watch?v=pAplQXk3dkU', 'Rotational core exercise with cable');
